include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 3000

build-review:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    DOCKER_BUILD_ARG_DEBUG: "debug"
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
    DOCKER_BUILD_ARG_DEBUG: "debug"
  only:
    refs:
      - develop

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
  only:
    refs:
      - master
      # this regexp will match release-tags
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-review"
    POSTGRES_ENABLED: 0
    # Allow using PR a environment
    K8S_SECRET_NODE_TLS_REJECT_UNAUTHORIZED: 0
    K8S_SECRET_OPEN_CITY_PROFILE_API_NAME: "https://api.hel.fi/auth/helsinkiprofile"
    K8S_SECRET_OPEN_CITY_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_NAME: "https://api.hel.fi/auth/jassariapi"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_URL: "https://jassari-api.test.kuva.hel.ninja/graphql/"

# This will enable staging ci-pipeline
staging:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-staging"
    # Allow using PR a environment
    K8S_SECRET_NODE_TLS_REJECT_UNAUTHORIZED: 0
    K8S_SECRET_OPEN_CITY_PROFILE_API_NAME: "https://api.hel.fi/auth/helsinkiprofile"
    K8S_SECRET_OPEN_CITY_PROFILE_API_URL: "https://profiili-api.test.kuva.hel.ninja/graphql/"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_NAME: "https://api.hel.fi/auth/jassariapi"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_URL: "https://jassari-api.test.kuva.hel.ninja/graphql/"
  only:
    refs:
      - develop

production:
  variables:
    DOCKER_IMAGE_NAME: "$CI_PROJECT_NAME-production"
    K8S_SECRET_OPEN_CITY_PROFILE_API_NAME: "https://api.hel.fi/auth/helsinkiprofile"
    K8S_SECRET_OPEN_CITY_PROFILE_API_URL: "https://api.hel.fi/profiili/graphql/"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_NAME: "https://api.hel.fi/auth/jassariapi"
    K8S_SECRET_YOUTH_MEMBERSHIP_API_URL: "https://jassari.api.hel.fi/graphql/"
